name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
        cache: 'maven'
    - run: ./mvnw clean install -B -V -e -ntp
