name: Build

on: push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v3
    - uses: albertus82/setup-java@main
      with:
        distribution: zulu
        java-version: 11
    - run: ./mvnw clean install -B -V -e -ntp
